[package]
name = "docker-mdbook"
version = "0.1.0"
authors = ["peaceiris <30958501+peaceiris@users.noreply.github.com>"]
edition = "2018"

[dependencies]
mdbook = "0.4.45"
mdbook-catppuccin = "3.0.0"
